#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import obappmenu

data = [
  {
    'name': 'GVim',
    'command': 'gvim',
    'category': 'Editors',
  },
  {
    'name': 'Firefox',
    'command': 'firefox',
    'category': 'Internet',
  },
  {
    'name': 'VimBrowser',
    'command': 'vimb',
    'category': 'Internet',
  },
  {
    'name': 'Thunderbird',
    'command': 'thunderbird',
    'category': 'Internet',
  },
  {
    'name': 'Pidgin',
    'command': 'pidgin',
    'category': 'Internet',
  }
]

obappmenu.obAppMenu(data)
