#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import os
import imp
from obappmenu import obAppMenu

HOMEDIR = os.path.expanduser('~/.config/openbox')
RCNAME = 'obappmenurc.py'

# FIXME load system-wide config

# Load user's config
homerc = os.path.join(HOMEDIR, RCNAME)
if (os.path.isfile(homerc)):
  imp.load_source('obappmenurc_local', homerc)
else:
  open(homerc, 'a').close()

obAppMenu.render()
